name: Test PlantUML Action
on: [push, pull_request]

jobs:
  process:
    name: Process PlantUML diagram
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Describe diagram
        run: 'printf "@startuml\nBob->Alice : hello\n@enduml" > diagram.txt'
      - name: Render diagram
        uses: ./
        with:
          args: '-tutxt diagram.txt'
      - name: Display diagram
        run: cat diagram.utxt
